package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Theme 0: Oro/Amarillo (Tulipán original)
val TulipYellowPrimary = Color(0xFFEAB308)
val TulipYellowSecondary = Color(0xFFFFD600)
val TulipYellowTertiary = Color(0xFFCA8A04)
val TulipCreamBackground = Color(0xFFFFFDF9)
val TulipCreamSurface = Color(0xFFFFFFFF)
val SoftCharcoalBrown = Color(0xFF422006)

val TulipDarkPrimary = Color(0xFFFFD600)
val TulipDarkSecondary = Color(0xFFF59E0B)
val TulipDarkTertiary = Color(0xFFD97706)
val TulipDarkBackground = Color(0xFF161512)
val TulipDarkSurface = Color(0xFF22201B)
val TulipDarkOnBackground = Color(0xFFFFFDF5)

// Theme 1: Gris Neutro (Austero y Minimalista)
val NeutralLightPrimary = Color(0xFF4B5563)
val NeutralLightSecondary = Color(0xFF6B7280)
val NeutralLightTertiary = Color(0xFF374151)
val NeutralLightBackground = Color(0xFFFAFAFA)
val NeutralLightSurface = Color(0xFFFFFFFF)
val NeutralTextColor = Color(0xFF1F2937)

val NeutralDarkPrimary = Color(0xFF9CA3AF)
val NeutralDarkSecondary = Color(0xFFD1D5DB)
val NeutralDarkTertiary = Color(0xFF4B5563)
val NeutralDarkBackground = Color(0xFF111827)
val NeutralDarkSurface = Color(0xFF1F2937)
val NeutralDarkOnBackground = Color(0xFFF9FAFB)

// Theme 2: Azul Océano (Masculino/Neutral)
val BlueLightPrimary = Color(0xFF1D4ED8)
val BlueLightSecondary = Color(0xFF2563EB)
val BlueLightTertiary = Color(0xFF1E40AF)
val BlueLightBackground = Color(0xFFF8FAFC)
val BlueLightSurface = Color(0xFFFFFFFF)
val BlueTextColor = Color(0xFF1E293B)

val BlueDarkPrimary = Color(0xFF60A5FA)
val BlueDarkSecondary = Color(0xFF93C5FD)
val BlueDarkTertiary = Color(0xFF1E3A8A)
val BlueDarkBackground = Color(0xFF0F172A)
val BlueDarkSurface = Color(0xFF1E293B)
val BlueDarkOnBackground = Color(0xFFF8FAFC)

// Theme 3: Verde Bosque (Neutral/Fresco)
val GreenLightPrimary = Color(0xFF059669)
val GreenLightSecondary = Color(0xFF10B981)
val GreenLightTertiary = Color(0xFF047857)
val GreenLightBackground = Color(0xFFF4FBF7)
val GreenLightSurface = Color(0xFFFFFFFF)
val GreenTextColor = Color(0xFF064E3B)

val GreenDarkPrimary = Color(0xFF34D399)
val GreenDarkSecondary = Color(0xFF6EE7B7)
val GreenDarkTertiary = Color(0xFF065F46)
val GreenDarkBackground = Color(0xFF064E3B)
val GreenDarkSurface = Color(0xFF0A5C46)
val GreenDarkOnBackground = Color(0xFFECFDF5)

// Theme 4: Rosa Pastel (Femenino)
val PinkLightPrimary = Color(0xFFDB2777)
val PinkLightSecondary = Color(0xFFEC4899)
val PinkLightTertiary = Color(0xFFBE185D)
val PinkLightBackground = Color(0xFFFFF1F2)
val PinkLightSurface = Color(0xFFFFFFFF)
val PinkTextColor = Color(0xFF4C0519)

val PinkDarkPrimary = Color(0xFFF472B6)
val PinkDarkSecondary = Color(0xFFF472B6)
val PinkDarkTertiary = Color(0xFFBE185D)
val PinkDarkBackground = Color(0xFF200C12)
val PinkDarkSurface = Color(0xFF28141A)
val PinkDarkOnBackground = Color(0xFFFFF1F2)

// Theme 5: Púrpura (Elegante/Moderno)
val PurpleLightPrimary = Color(0xFF7C3AED)
val PurpleLightSecondary = Color(0xFF8B5CF6)
val PurpleLightTertiary = Color(0xFF5B21B6)
val PurpleLightBackground = Color(0xFFFAF5FF)
val PurpleLightSurface = Color(0xFFFFFFFF)
val PurpleTextColor = Color(0xFF2E1065)

val PurpleDarkPrimary = Color(0xFFC084FC)
val PurpleDarkSecondary = Color(0xFFD8B4FE)
val PurpleDarkTertiary = Color(0xFF4C1D95)
val PurpleDarkBackground = Color(0xFF0F0B1E)
val PurpleDarkSurface = Color(0xFF1D142E)
val PurpleDarkOnBackground = Color(0xFFFAF5FF)

// Subject general pastel colors (Neutral/Aesthetic)
val SubjectPastelYellow = Color(0xFFFFE082)
val SubjectPastelOrange = Color(0xFFFFB74D)
val SubjectPastelPink = Color(0xFFF48FB1)
val SubjectPastelGreen = Color(0xFF81C784)
val SubjectPastelBlue = Color(0xFF64B5F6)
val SubjectPastelPurple = Color(0xFFCE93D8)
